name: Publish with VSCE

on:
  push:
    branches:
    - master
#    release:
#      types: [published]
#
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: vsce publish
        uses: sigma/vsce-publish-action@v0.0.1
        with:
          GITHUB_REPOSITORY
          vsce_token: ${{ secrets.VSCE_TOKEN }}
      
